# Generated by Django 3.2.1 on 2021-05-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onefin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collections',
            name='movies',
        ),
        migrations.AddField(
            model_name='collections',
            name='movies',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
