# Generated by Django 3.2.1 on 2021-05-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onefin', '0002_auto_20210506_0026'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavouriteGenres',
        ),
    ]
